# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Program Files (x86)\Qt Designer\my\2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(327, 342)
        MainWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Main = QtWidgets.QVBoxLayout()
        self.Main.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Main.setObjectName("Main")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Main.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.main)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Main.addWidget(self.label_2)
        self.NameInput = QtWidgets.QLineEdit(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameInput.sizePolicy().hasHeightForWidth())
        self.NameInput.setSizePolicy(sizePolicy)
        self.NameInput.setMinimumSize(QtCore.QSize(165, 0))
        self.NameInput.setMaxLength(1024)
        self.NameInput.setFrame(True)
        self.NameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.NameInput.setClearButtonEnabled(False)
        self.NameInput.setObjectName("NameInput")
        self.Main.addWidget(self.NameInput)
        self.line_1 = QtWidgets.QFrame(self.main)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.Main.addWidget(self.line_1)
        self.MoneyLayout = QtWidgets.QHBoxLayout()
        self.MoneyLayout.setContentsMargins(-1, 4, -1, -1)
        self.MoneyLayout.setObjectName("MoneyLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.MoneyLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.main)
        self.label.setObjectName("label")
        self.MoneyLayout.addWidget(self.label)
        self.MoneySpinbox = QtWidgets.QSpinBox(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoneySpinbox.sizePolicy().hasHeightForWidth())
        self.MoneySpinbox.setSizePolicy(sizePolicy)
        self.MoneySpinbox.setWrapping(False)
        self.MoneySpinbox.setFrame(True)
        self.MoneySpinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MoneySpinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.MoneySpinbox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.MoneySpinbox.setMaximum(999999)
        self.MoneySpinbox.setSingleStep(10)
        self.MoneySpinbox.setObjectName("MoneySpinbox")
        self.MoneyLayout.addWidget(self.MoneySpinbox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.MoneyLayout.addItem(spacerItem2)
        self.Main.addLayout(self.MoneyLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Main.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.Main)
        self.tabWidget.addTab(self.main, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 327, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Player name:"))
        self.label.setText(_translate("MainWindow", "Money:"))
        self.MoneySpinbox.setSuffix(_translate("MainWindow", " ₽"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("MainWindow", "Main"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
